// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA65IKwMcj1WvUCkKiGSZAs0g0207Lwgic',
    appId: '1:863861034348:web:c2f0cee5eeeac1f777f749',
    messagingSenderId: '863861034348',
    projectId: 'homework2mad',
    authDomain: 'homework2mad.firebaseapp.com',
    storageBucket: 'homework2mad.firebasestorage.app',
    measurementId: 'G-EB4154FVZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx-LirQjdYx2aHyup2OnYm06UgV5cByG4',
    appId: '1:863861034348:android:34fcb2859f6b516077f749',
    messagingSenderId: '863861034348',
    projectId: 'homework2mad',
    storageBucket: 'homework2mad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzP-2c8HVQ4EBZpvEN7JK5WQyj0stZcxo',
    appId: '1:863861034348:ios:858358abf9770f9b77f749',
    messagingSenderId: '863861034348',
    projectId: 'homework2mad',
    storageBucket: 'homework2mad.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzP-2c8HVQ4EBZpvEN7JK5WQyj0stZcxo',
    appId: '1:863861034348:ios:858358abf9770f9b77f749',
    messagingSenderId: '863861034348',
    projectId: 'homework2mad',
    storageBucket: 'homework2mad.firebasestorage.app',
    iosBundleId: 'com.example.hw2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA65IKwMcj1WvUCkKiGSZAs0g0207Lwgic',
    appId: '1:863861034348:web:40b43484c48edcef77f749',
    messagingSenderId: '863861034348',
    projectId: 'homework2mad',
    authDomain: 'homework2mad.firebaseapp.com',
    storageBucket: 'homework2mad.firebasestorage.app',
    measurementId: 'G-YQS9SMJEEM',
  );

}